# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "test01" do |test01|
    test01.vm.box = "jeqo/oracle-linux-6"

    test01.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "512"
    end

    test01.vm.provision "ansible" do |ansible|
      ansible.playbook = "install-configure-filebeat-oracle-linux-6.yml"
      ansible.galaxy_role_file = "roles.yml"
    end
  end
end
